level_0 = {
    'terrain': '../levels/0/level_0_terrain.csv',
    'coins': '../levels/0/level_0_coins.csv',
    'trees': '../levels/0/level_0_trees.csv',
    'enemies': '../levels/0/level_0_enemies.csv',
    'constraints': '../levels/0/level_0_constraints.csv',
    'player': '../levels/0/level_0_player.csv',
    'brush': '../levels/0/level_0_brush.csv',
    'stump': '../levels/0/level_0_stumps.csv',
    'node_pos':(110,650),
    'unlock':1,
    'node_art': '../PixelArt/overworld/nodes/0',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/lizard_gray.png'}
level_1 = {
    'terrain': '../levels/1/level_1_terrain.csv',
    'coins': '../levels/1/level_1_coins.csv',
    'trees': '../levels/1/level_1_trees.csv',
    'enemies': '../levels/1/level_1_enemies.csv',
    'constraints': '../levels/1/level_1_constraints.csv',
    'player': '../levels/1/level_1_player.csv',
    'brush': '../levels/1/level_1_brush.csv',
    'stump': '../levels/1/level_1_stumps.csv',
    'node_pos':(300,550),
    'unlock':2,
    'node_art': '../PixelArt/overworld/nodes/1',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/turt_gray.png'}
level_2 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'trees': '../levels/2/level_2_trees.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'brush': '../levels/2/level_2_brush.csv',
    'stump': '../levels/2/level_2_stumps.csv',
    'node_pos':(200,220),
    'unlock':3,
    'node_art': '../PixelArt/overworld/nodes/2',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/lion_gray.png'}
level_3 = {
    'terrain': '../levels/3/level_3_terrain.csv',
    'coins': '../levels/3/level_3_coins.csv',
    'trees': '../levels/3/level_3_trees.csv',
    'enemies': '../levels/3/level_3_enemies.csv',
    'constraints': '../levels/3/level_3_constraints.csv',
    'player': '../levels/3/level_3_player.csv',
    'brush': '../levels/3/level_3_brush.csv',
    'stump': '../levels/3/level_3_stumps.csv',
    'node_pos':(375,150),
    'unlock':4,
    'node_art': '../PixelArt/overworld/nodes/3',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/monk_gray.png'}
level_4 = {
    'terrain': '../levels/4/level_4_terrain.csv',
    'coins': '../levels/4/level_4_coins.csv',
    'trees': '../levels/4/level_4_trees.csv',
    'enemies': '../levels/4/level_4_enemies.csv',
    'constraints': '../levels/4/level_4_constraints.csv',
    'player': '../levels/4/level_4_player.csv',
    'brush': '../levels/4/level_4_brush.csv',
    'stump': '../levels/4/level_4_stumps.csv',
    'node_pos':(550,200),
    'unlock':5,
    'node_art': '../PixelArt/enemy/monke',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/monke_gray.png'}
level_5 = {
    'terrain': '../levels/5/level_5_terrain.csv',
    'coins': '../levels/5/level_5_coins.csv',
    'trees': '../levels/5/level_5_trees.csv',
    'enemies': '../levels/5/level_5_enemies.csv',
    'constraints': '../levels/5/level_5_constraints.csv',
    'player': '../levels/5/level_5_player.csv',
    'brush': '../levels/5/level_5_brush.csv',
    'stump': '../levels/5/level_5_stumps.csv',
    'node_pos':(850,450),
    'unlock':6,
    'node_art': '../PixelArt/enemy/flow',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/flow_gray.png'}
level_6 = {
    'terrain': '../levels/6/level_6_terrain.csv',
    'coins': '../levels/6/level_6_coins.csv',
    'trees': '../levels/6/level_6_trees.csv',
    'enemies': '../levels/6/level_6_enemies.csv',
    'constraints': '../levels/6/level_6_constraints.csv',
    'player': '../levels/6/level_6_player.csv',
    'brush': '../levels/6/level_6_brush.csv',
    'stump': '../levels/6/level_6_stumps.csv',
    'node_pos':(1000,500),
    'unlock':7,
    'node_art': '../PixelArt/enemy/cyclops',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/cyclops_gray.png'}
level_7 = {
    'terrain': '../levels/7/level_7_terrain.csv',
    'coins': '../levels/7/level_7_coins.csv',
    'trees': '../levels/7/level_7_trees.csv',
    'enemies': '../levels/7/level_7_enemies.csv',
    'constraints': '../levels/7/level_7_constraints.csv',
    'player': '../levels/7/level_7_player.csv',
    'brush': '../levels/7/level_7_brush.csv',
    'stump': '../levels/7/level_7_stumps.csv',
    'node_pos':(1150,100),
    'unlock':7,
    'node_art': '../PixelArt/enemy/crab',
    'locked_node_art': '../PixelArt/overworld/nodes/gray/crab_gray.png'}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5,
    6: level_6,
    7: level_7}


